# Generated by Django 3.1.4 on 2020-12-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_contester',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_organizer',
        ),
        migrations.DeleteModel(
            name='Contestant',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
