# Generated by Django 3.1.4 on 2020-12-26 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='about',
        ),
        migrations.AddField(
            model_name='contest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 23, 50, 26, 283535)),
        ),
        migrations.AddField(
            model_name='contestant',
            name='manifesto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
