# Generated by Django 3.1.4 on 2020-12-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20201227_1749'),
        ('contests', '0003_auto_20201227_1548'),
    ]

    operations = [
    ]
