# Generated by Django 3.1.4 on 2020-12-28 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_merge_20201227_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 0, 10, 58, 466023)),
        ),
    ]
